---
# tasks file for homestead

- name: Configuration locale de clearwater
  shell: mkdir -p /etc/clearwater; bash -c ' echo -e "local_ip={{ansible_eth0.ipv4.address}}\npublic_ip={{pub_homestead}}\npublic_hostname=homestead.{{domain_name}}\netcd_cluster=\"{{etcd_cluster}}\"" > /etc/clearwater/local_config'
  tags: test

- name: Open up ports
  shell: ufw --force enable ; ufw allow 22/tcp ; ufw allow 2380/tcp ; ufw allow 161:162/udp ; ufw allow 4000/tcp ; ufw allow 3478 ; ufw allow 5060 ; ufw allow 8888/tcp ; ufw allow 7000/tcp ; ufw allow  8889/tcp
  tags: test

- name: install homestead packets
  apt: name=homestead force=yes state=present
  tags: test
- name: install homestead-prov packets
  apt: name=homestead-prov force=yes state=present
  tags: test
- name: install clearwater-prov-tools packets
  apt: name=clearwater-prov-tools force=yes state=present
  tags: test
- name: install clearwater-config-manager
  apt: name=clearwater-management force=yes state=present
  tags: test
- name: wait for etcd
  command: /usr/share/clearwater/clearwater-etcd/scripts/wait_for_etcd
