---
  # Bring stack Down
  - hosts: ellis
    become: true
    tasks:
      - service: name={{item}} state=stopped
        with_items:
          - ellis
          - clearwater-etcd
          - dnsmasq

  - hosts: bono
    become: true
    tasks:
      - service: name={{item}} state=stopped
        with_items:
          - bono
          - clearwater-etcd
          - dnsmasq


  - hosts: sprout
    become: true
    tasks:
      - service: name={{item}} state=stopped
        with_items:
          - sprout
          - clearwater-etcd
          - dnsmasq



  - hosts: homer
    become: true
    tasks:
      - service: name={{item}} state=stopped
        with_items:
          - homer
          - clearwater-etcd
          - dnsmasq


  - hosts: homestead
    become: true
    tasks:
      - service: name={{item}} state=stopped
        with_items:
          - homestead
          - clearwater-etcd
          - dnsmasq

  - hosts: ralf
    become: true
    tasks:
      - service: name={{item}} state=stopped
        with_items:
          - ralf
          - clearwater-etcd
          - dnsmasq

  - hosts: bind
    become: true
    tasks:
      - service: name={{item}} state=stopped
        with_items:
          - bind9


# Restarted
  # Bring stack Up
  - hosts: ellis
    become: true
    tasks:
      - service: name={{item}} state=started
        with_items:
          - ellis
          - clearwater-etcd
          - dnsmasq

  - hosts: bono
    become: true
    tasks:
      - service: name={{item}} state=started
        with_items:
          - bono
          - clearwater-etcd
          - dnsmasq


  - hosts: sprout
    become: true
    tasks:
      - service: name={{item}} state=started
        with_items:
          - sprout
          - clearwater-etcd
          - dnsmasq



  - hosts: homer
    become: true
    tasks:
      - service: name={{item}} state=started
        with_items:
          - homer
          - clearwater-etcd
          - dnsmasq


  - hosts: homestead
    become: true
    tasks:
      - service: name={{item}} state=started
        with_items:
          - homestead
          - clearwater-etcd
          - dnsmasq

  - hosts: ralf
    become: true
    tasks:
      - service: name={{item}} state=started
        with_items:
          - ralf
          - clearwater-etcd
          - dnsmasq

  - hosts: bind
    become: true
    tasks:
      - service: name={{item}} state=started
        with_items:
          - bind9
